# Imbalanced Dataset

A dataset with unequal class distribution

In [1]:
# importing libraries/dependancies
import numpy as np
import pandas as pd

In [2]:
# loading the dataset to a dataframe
credit_card = pd.read_csv('credit_data.csv')

In [3]:
credit_card.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
credit_card.shape

(284807, 31)

In [5]:
credit_card.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [7]:
# Distribution of the two classes
credit_card['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

This is a highly imbalanced dataset

0 --- Legit transaction
1 --- Fradulent transaction

### Separating the legit and fradulent transactions

In [8]:
legit = credit_card[credit_card.Class == 0]
fraud = credit_card[credit_card.Class == 1]

In [9]:
print(legit.shape)

(284315, 31)

In [10]:
print(fraud.shape)

(492, 31)

## Under-sampling

Building a sample dataset containing similar distribution of legit and fradulent transactions
No of fraud ----> 492

In [11]:
legit_sample = legit.sample(n=492)

In [12]:
print(legit_sample.shape)

(492, 31)

In [13]:
legit_sample.shape

(492, 31)

### Concatenete the two Data Frames

In [14]:
new_dataset = pd.concat([legit_sample, fraud], axis = 0)

In [15]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [16]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
165424,117424.0,2.120131,0.009061,-2.244996,0.093854,0.877164,-0.607021,0.520745,-0.269798,-0.026291,...,0.110672,0.444455,-0.057494,0.354050,0.414981,0.688685,-0.124384,-0.093622,0.76,0
168643,119321.0,-0.854528,1.627294,1.693644,2.473419,1.242119,-0.010633,1.225972,0.023620,-2.574381,...,0.296161,0.683838,-0.584494,0.078528,0.895426,0.228087,-0.025059,0.041560,1.00,0
69321,53367.0,-0.728260,0.578475,1.555566,-1.424587,0.036555,-0.581717,0.529745,0.121198,-0.249932,...,-0.031587,-0.145897,-0.054144,0.027357,-0.316437,0.721647,0.242378,0.164332,26.38,0
28563,35056.0,-1.239401,1.871972,0.464516,0.836551,-0.284590,-0.324412,0.124794,0.631690,-1.001683,...,0.335331,0.708889,-0.042615,0.124497,-0.277603,-0.343868,-0.456218,0.029624,13.34,0
111740,72346.0,-0.485170,0.935395,1.448144,1.317904,0.267815,-0.004178,0.543711,0.120834,-0.274843,...,-0.026831,0.256910,-0.128751,0.095789,-0.088303,-0.223365,0.425055,0.206328,10.17,0

In [17]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [18]:
new_dataset.shape

(984, 31)